---
title: "Pictogram : Case of Korea Income"
author: "coop711"
date: "2015년 4월 16일"
output: html_document
---

Mean and Median Korea Income 2003-2009
---------------------------------------

Load Data

```{r}
load("income_03_09.rda")
ls()
```

Set up a data matrix

```{r}
income.03.09<-cbind(mean=mean.income, median=median.income)
income.03.09
rownames(income.03.09)<-2003:2009
income.03.09
```

Compare the two plots

```{r fig.width=10, fig.height=5}
par(mfrow=c(1,2))
plot(mean~as.numeric(rownames(income.03.09)), data=income.03.09, type="b", ylim=c(2500,3100), ann=F, xlab="", ylab="")
title(xlab="Year", ylab="Income (10,000 won)")
lines(median~as.numeric(rownames(income.03.09)), data=income.03.09, type="b", lty=2)
legend("topleft", inset=0.02, lty=1:2, legend=c("mean", "median")) 
plot(mean~as.numeric(rownames(income.03.09)), data=income.03.09, type="b", ylim=c(2000,3500), ann=F, xlab="", ylab="")
title(xlab="Year", ylab="Income (10,000 won)")
lines(median~as.numeric(rownames(income.03.09)), data=income.03.09, type="b", lty=2)
legend("topleft", inset=0.02, lty=1:2, legend=c("mean", "median")) 
mtext("Pictogram : Case of Korea Income", side=3, outer=TRUE, line=-3)
par(mfrow=c(1,1))
```

Compute median/mean ratio

```{r}
options(digits=3)
median.mean.ratio<-median.income/mean.income*100
median.mean.ratio
```

Compare the two plots

```{r fig.width=10, fig.height=5}
par(mfrow=c(1,2))
plot(median.mean.ratio~as.numeric(rownames(income.03.09)), type="b", xlab="Year", ylab="Median/Mean Ratio(%)")
plot(median.mean.ratio~as.numeric(rownames(income.03.09)), type="b", xlab="Year", ylab="Median/Mean Ratio(%)", ylim=c(50,100))
mtext("Pictogram : Case of Median/Mean Ratio", side=3, outer=TRUE, line=-3)
par(mfrow=c(1,1))
```
